# Beispiel Konfiguration

PORT = 13001
IP = 0.0.0.0

# Captcha
CAPTCHA_ACTIVE = 1
CAPTCHA_FAIL_LIMIT = 3
CAPTCHA_BLOCK_MIN = 5

# Register
REGISTER_COOLDOWN = 5

# Datenbank (Beispielwerte)
SQL_HOST = localhost
SQL_USER = user
SQL_PASS = pass
SQL_DB = account